"""empty message

Revision ID: 4b25a41a3943
Revises: 6586bcfa720d
Create Date: 2023-07-17 13:51:17.996797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b25a41a3943'
down_revision = '6586bcfa720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('rush_yards', sa.String(), nullable=False),
    sa.Column('receptions', sa.String(), nullable=False),
    sa.Column('receiving_yards', sa.String(), nullable=False),
    sa.Column('finish', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('expert_analysis', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###
