"""empty message

Revision ID: 7cdfe4e740a8
Revises: 4b25a41a3943
Create Date: 2023-07-17 15:05:14.639961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdfe4e740a8'
down_revision = '4b25a41a3943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rushyards', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('receivingyards', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('expertanalysis', sa.String(), nullable=False))
        batch_op.drop_column('receiving_yards')
        batch_op.drop_column('expert_analysis')
        batch_op.drop_column('rush_yards')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rush_yards', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('expert_analysis', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('receiving_yards', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('expertanalysis')
        batch_op.drop_column('receivingyards')
        batch_op.drop_column('rushyards')

    # ### end Alembic commands ###
