"""empty message

Revision ID: 8681906c7dd4
Revises: 7cdfe4e740a8
Create Date: 2023-07-17 16:35:30.918959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8681906c7dd4'
down_revision = '7cdfe4e740a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rushyards',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('receptions',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('receivingyards',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('finish',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('expertanalysis',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('expertanalysis',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('finish',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('receivingyards',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('receptions',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('rushyards',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
